name: vortax_labs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.10.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.4
  network_info_plus: ^7.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  # Ensures the Material Icons font is included with your application.
  uses-material-design: true

  # App image assets live here.
  assets:
    - assets/images/